data:
  train_files: /projects/p32958/chengxuan/ProgressLM/data/train/rl/new/final_20k_ready.jsonl
  val_files: /projects/p32958/chengxuan/ProgressLM/data/train/rl/new/final_20k_ready.jsonl
  prompt_key: user_prompt
  answer_key: answer
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 2.0
  max_prompt_length: 20000
  max_response_length: 8192
  rollout_batch_size: 48
  mini_rollout_batch_size: null
  val_batch_size: 32
  format_prompt: null
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 3136
  max_pixels: 12845056
  filter_overlong_prompts: false
  filter_overlong_prompts_workers: 128

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  kl_type: fixed
  kl_target: 0.1
  online_filtering: false
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    global_batch_size: 48
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 2
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: /gpfs/projects/b1222/userdata/canyu/.cache/huggingface/hub/models--Qwen--Qwen2.5-VL-3B-Instruct/snapshots/66285546d2b821cf421d4f5eb2576359d3770cd3
      tokenizer_path: null
      enable_gradient_checkpointing: true
      trust_remote_code: true
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 8
    temperature: 0.6
    top_p: 0.9
    limit_images: 50
    gpu_memory_utilization: 0.7
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    disable_tqdm: false
    max_num_batched_tokens: 40000
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  reward:
    reward_type: batch
    reward_function: ./progresslm/reward/visual_demo_reward.py:compute_score

trainer:
  total_epochs: 2
  max_steps: null
  project_name: progresslm_rl_3b_20k_new
  experiment_name: qwen2p5vl3b
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 4
  max_try_make_batch: 20
  val_freq: -1
  val_before_train: false
  val_only: false
  val_generations_to_log: 2
  save_freq: 10
  save_limit: 5
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
